### ISSUE TITLE
Investigate sharing HTTP requests between calls to `get_course_info` in `datagen`

### ISSUE THREAD

**Issue by atcupps** [atcupps/Jupiterp#2]
Currently, `fn get_course_info` in `main.rs` of `datagen` creates a separate request for each course. This is highly inefficient; it may be possible to share the response of a single request between several `get_course_info` calls, perhaps between all courses sharing the same course prefix or maybe even all courses. My earlier attempts to do this failed, but this should be investigated further.

**Comment by srithon** [comment]
Hey, I looked into this for one of my own projects and you can actually reduce the number of requests for scraping section information significantly by using the `sections` endpoint used by their "Show All Sections" button on the schedule of classes page for a given department. Here's a request for getting section information for every current CMSC course:
```
https://app.testudo.umd.edu/soc/202401/sections?courseIds=CMSC100,CMSC106,CMSC115,CMSC116,CMSC122,CMSC125,CMSC131,CMSC132,CMSC142,CMSC216,CMSC250,CMSC250H,CMSC320,CMSC330,CMSC335,CMSC351,CMSC351H,CMSC388J,CMSC389G,CMSC389O,CMSC389P,CMSC396H,CMSC398E,CMSC398L,CMSC398M,CMSC398Q,CMSC398R,CMSC401,CMSC411,CMSC412,CMSC414,CMSC416,CMSC417,CMSC420,CMSC421,CMSC422,CMSC423,CMSC424,CMSC425,CMSC426,CMSC427,CMSC430,CMSC433,CMSC434,CMSC435,CMSC436,CMSC451,CMSC452,CMSC454,CMSC456,CMSC457,CMSC460,CMSC466,CMSC470,CMSC472,CMSC475,CMSC477,CMSC498C,CMSC498F,CMSC498Y,CMSC616,CMSC624,CMSC651,CMSC661,CMSC701,CMSC711,CMSC720,CMSC733,CMSC764,CMSC800,CMSC818G,CMSC818R,CMSC828A,CMSC828J,CMSC838C,CMSC838L,CMSC839A,CMSC848B,CMSC848G,CMSC848J,CMSC858G,CMSC858N,CMSC858O
```

Here's sample output for a smaller example: `https://app.testudo.umd.edu/soc/202401/sections?courseIds=CMSC100`
```html
<div>
  <div id="CMSC100" class="course-sections">
    <div class="sections-container">
      <div class="sections sixteen colgrid">
        <div class="section delivery-f2f">
          <input type="hidden" name="sectionId" value="0201" />
          <div class="section-info-container">
            <div class="row">
              <div class="section-id-container two columns">
                <span class="section-id">
                  0201
                </span>
              </div>
              <div class="section-instructors-container five columns">
                <span class="section-instructors">
                <span class="section-instructor">Noah Owens</span>
                </span>
              </div>
              <div class="seats-info-group six columns">
                <div>
                  <span class="section-info-label">Seats</span>
                  <span class="seats-info">
                    <span class="total-seats">
                      (<span class="seats-info-label">Total:</span>
                    <span class="total-seats-count">40</span>,
                    </span>
                    <span class="open-seats has-open-seats">
                    <span class="seats-info-label">Open:</span>
                    <span class="open-seats-count">28</span>,
                    </span>
                    <span class="waitlist ">
                      <a href="https://registrar.umd.edu/registration/register-classes/waitlist-hold-file">
                        <span class="seats-info-label"> Waitlist:</span>
                        <span class="waitlist-count">0</span>
                      </a>)
                    </span>
                  </span>
                </div>
              </div>
              <div class="two columns section-action-links-container2">
                <a href="javascript:void(0)" onclick="SocJs.saveSection(this, 'CMSC100', '0201', '/soc');" class="saved-course-section-toggle-link" title="Add to My Saved List">
                  <img src="/soc/resources/images/unsaved-star.png" />
                </a>
                <a href="#" class="bookstore-link">
                  <img src="/soc/resources/images/bookstore.png" alt="Bookstore" title="Bookstore">
                </a>
              </div>
            </div>
          </div> <!-- end section-info-container -->
          <div class="class-days-container">
            <div class="row">
              <div class="section-day-time-group push_two five columns">
                <span class="section-days">F</span>
                <span class="class-start-time">12:00pm</span> - <span class="class-end-time">12:50pm</span>
              </div>
              <div class="section-class-building-group push_one three columns">
                <span class="class-building">
                  <a target="_blank" style="color:#A81919;"><span class="building-code">IRB</span>
                  <span class="class-room">2207</span></a>
                </span>
              </div>
            </div> 
          </div> 
        </div> 
      </div>
    </div>
  </div>
</div>
```

This endpoint isn't restricted to a single department; you can add course codes from any department. This method is bounded only by the Max URI length defined by the webserver; you cannot add an unlimited number of course codes to a single request because it will go over the limit. It seems that Testudo's running on Apache Webserver (there are services online which let you plug in a URL and will try to figure out which webserver it's running), which has a default Max URI length of 8177. I still have to confirm this, but knowing UMD they probably didn't change the default.

To figure out how many requests we would need to scrape everything, we need a bit of math.
First, there are a total of 4594 current courses at UMD.
I used the data you scraped and plugged it into `jq` to get this number:
```sh
$ jq 'map(.courses | map(.code)) | add | length' < /tmp/department.json
4594
```

In total, a comma-separated list of all the course codes takes 37951.
```sh
$ jq --raw-output 'map(.courses | map(.code)) | add | join(",")' < /tmp/department.json | wc -c
37951
```

If the max URI length is 8177, then we can approximate the number of requests with the following formula (approximation because we're ignoring the leading `https://app.testudo.umd.edu/soc/202401/sections?courseIds=` prefix for each request, which is 58 characters:
$$\text{numRequests} \approx \frac{37951}{8177} = 4.64$$

This is a big improvement over the current approach, but it does lack some of the details you would get by directly going to the course page individually (as you currently do in `get_course_info`). However, you could work around this by collecting these missing details in `get_courses`, since the overall schedule of classes page contains all the information relating to courses with the _exception_ of the section information, which we are now able to compute efficiently!

Unfortunately, I'm note sure there's a way to improve `get_courses` to use less than `numDepartments` requests. However, one thing to note is that the list of courses is largely static compared to the list of sections for courses, and so theoretically you could reduce the frequency of scraping without losing too much.

---

All of that aside, I really like the way you implemented this project! The way you used GitHub actions on a cron schedule to scrape the data, and then had it automatically create a pull request and deploy to Vercel was super interesting and I never would have thought of it myself. For my own project, I was initially considering using AWS EventBridge to trigger Lambda functions on a schedule for doing the scraping (just praying that it stays within the free tier), but I'm definitely going to opt for this approach instead.

**Comment by atcupps** [comment]
@srithon thanks for sharing the research you've put into this! This is incredibly helpful. And, glad to hear that seeing my deployment method was helpful to you. I'll say just so you know that I wasn't able to get GitHub actions to automatically merge pull requests (this might be because I didn't look into it too deeply but it may also just be a security limitation preventing automatic merging of code), so I still have to merge them manually which I usually just do using the GitHub app on my phone. If you need the process to be more automated then you might want to consider using AWS or some other cloud solution instead.

**Comment by srithon** [comment]
@atcupps of course! Thanks for letting me know about your GitHub actions workflow. A quick Google search found [automerge-action](https://github.com/pascalgn/automerge-action) which may be of use. If not (and also assuming that this is something that even needs fixing), another option could be to move the scraped data out of the repository itself and into some static file hosting service, or alternatively to push the scraped assets into GitHub Releases, as daily automated releases. These approaches would require you to fetch the data from within your code, but would likely come as a slight optimization, since it would mean that the core app code would remain static day-to-day and thus could stay in the browser cache, rather than having the entire bundle invalidated and retransmitted. For my own project, I'm now considering using GitHub Actions to scrape the data, uploading it to something like Google Firestore to be fetched by users; however, my use case is slightly different because I explicitly want to track data over time, and thus my data would constantly be growing.

**Comment by atcupps** [comment]
Using the `sections` query in the URL gives the following information:
- course code (via `div id`)
- section code
- whether classes are online or in-person
- class days and times
- class locations

The following is currently collected and important information that is not shown when using the `sections` query:
- course title/name
- course # of credits
- course GenEds
- course description

Additionally, the following issues are noteworthy when using `sections` query:
- courses with no sections are not shown at all on the page

Precursory examination indicates this is a viable approach to minimize the amount of HTTP requests required. Section information can be requested in batches of classes using the `sections` query approach while course information can also be requested in batches using the existing scraping since none of the information is section-specific. I expect the best approach from an organizational standpoint would be to make two requests for each department (one for section-specific information and one for course info). Since this investigation is now done, I'm closing this issue and creating new issues for relevant actionable tasks
